version: '3'

services:
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:3.4
    restart: always
    volumes:
      - ./mongodata:/data/db
  core:
    container_name: openhim-core
    image: kuunika/openhim-core:0.0.1
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    restart: always
    volumes: 
      - ./certificates:/usr/local/share/ca-certificates
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
  
  console:
    container_name: openhim-console
    image: kuunika/openhim-console:0.0.1
    ports:
        - "9000:80"
    restart: always
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
    
